### ISSUE TITLE
csv file format

### ISSUE THREAD

**Issue by zhaohandd** [multimodallearning/stroke-prediction#1]
clinical_cleaned.csv

**Comment by theluckylucas** [comment]
Hi,
CSV includes the following clinical data:

CaseNo,TOtoTA in h,TAtoRECA in h,NIHSS,Age in y,Sex

I.e., Case Number, Time from onset to admission in hours, Time from admission to recanalisation in hours, NIHSS score, age in years, and a bit indicating male/female. The above line is the first line (header) in the csv, so data starts not in csv[0] but csv[1] line.

In fact, only the two times are considered within the source code for the interpolation.

**Comment by XmaNm** [comment]
could you share the dataset which used in your code？

**Comment by theluckylucas** [comment]
Unfortunately, it's an institutional dataset with restriction to share. You can use another stroke segmentation dataset by writing a custom dataloader and use it at https://github.com/multimodallearning/stroke-prediction/blob/58da5be2c16637d47587cb09ac87ddebf028e093/train_shape_reconstruction.py#L55
